services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/project
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - HUGO_ENV=production