# Dockerfile.dev

FROM ghcr.io/gohugoio/hugo:latest

# Passer en utilisateur root pour installer des paquets
USER root

# Installer les dépendances
RUN apk add --no-cache bash curl git

# Définir le répertoire de travail
WORKDIR /project

# Copier les fichiers du projet
COPY app/ /project

# Exposer le port utilisé par Hugo
EXPOSE 1313

# Commande par défaut
CMD ["server", "--bind", "0.0.0.0", "--port", "1313", "--disableFastRender"]